name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dishachaudhari/docker:latest
    - name: push docker image
      run: docker login -u dishachaudhari -p ${{ secrets. DOCKER}} && docker push dishachaudhari/docker:latest
